
package view;

import entity.IstekTipleri;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DBConnection;


public class istekTipleri extends javax.swing.JFrame {

   
    DefaultTableModel model;

    public istekTipleri() {
        initComponents();
        tabloyudoldur();
    }
    private DBConnection db;

    public DBConnection getDb() {

        if (db == null) {
            this.db = new DBConnection();
        }
        return db;
    }

    public void setDb(DBConnection connection) {
        this.db = connection;
    }

    public void tabloyudoldur() {
        model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        try {
            ArrayList<IstekTipleri> kayitlar = getIstekTipleri();
            for (IstekTipleri rnd : kayitlar) {
                Object[] row = {rnd.getIstek_tipi()};
                model.addRow(row);
            }
        } catch (SQLException ex) {

        }
    }

    public ArrayList<IstekTipleri> getIstekTipleri() throws SQLException {
        Connection connection = null;
        DBConnection db = new DBConnection();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<IstekTipleri> kayitlar = null;

        try {
            connection = db.connect();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select * from istek_tipleri");
            kayitlar = new ArrayList<IstekTipleri>();

            while (resultSet.next()) {
                kayitlar.add(new IstekTipleri(
                        resultSet.getString("istek_tipi")
                ));
            }

        } catch (SQLException exception) {

        } finally {
            statement.close();
            connection.close();
        }
        return kayitlar;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        istektipitxt = new javax.swing.JTextField();
        secbtn = new javax.swing.JButton();
        eklebtn = new javax.swing.JButton();
        silbtn = new javax.swing.JButton();
        guncellebtn = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "İstek Tipi"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jLabel1.setText("İSTEK TİPİ:");

        secbtn.setText("SEÇ");
        secbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secbtnActionPerformed(evt);
            }
        });

        eklebtn.setText("EKLE");
        eklebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebtnActionPerformed(evt);
            }
        });

        silbtn.setText("SİL");
        silbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silbtnActionPerformed(evt);
            }
        });

        guncellebtn.setText("GÜNCELLE");
        guncellebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncellebtnActionPerformed(evt);
            }
        });

        lbl.setText("uyarı mesajı");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(istektipitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guncellebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(silbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eklebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(secbtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(eklebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(silbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(istektipitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guncellebtn)
                        .addGap(38, 38, 38)
                        .addComponent(secbtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     int idsi;
    private void secbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secbtnActionPerformed
        int tablo1satir = tbl.getSelectedRow();
        istektipitxt.setText(String.valueOf(tbl.getValueAt(tablo1satir, 0)));
        String istekadi;
        istekadi = istektipitxt.getText();
        int id = 0;
        try {
            Statement st = this.getDb().connect().createStatement();
            ResultSet rst = st.executeQuery("select * from istek_tipleri");
            while (rst.next()) {
                if (rst.getString("istek_tipi").equals(istekadi)) {
                    id = rst.getInt("istek_tipi_id");
                }
            }
        } catch (Exception e) {
            e.getMessage();
        }
        idsi = id;
    }//GEN-LAST:event_secbtnActionPerformed

    private void eklebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebtnActionPerformed
        
         int sayac = 0;
        try {
            Statement st = this.getDb().connect().createStatement();
            ResultSet rst = st.executeQuery("select * from istek_tipleri");
            while (rst.next()) {
                if (istektipitxt.getText().equals(rst.getString("istek_tipi"))) {
                    JOptionPane.showMessageDialog(null, "Bu istek tipi zaten mevcut");
                    sayac++;
                }
            }
            if (sayac != 1) {
                st.executeUpdate("insert into istek_tipleri(istek_tipi) values ('"
                    + istektipitxt.getText() + "')");
                tabloyudoldur();
                lbl.setText("İstek tipi başarılı bir şekilde eklendi");
            }
        } catch (Exception e) {
            e.getMessage();
        }
        
    }//GEN-LAST:event_eklebtnActionPerformed

    private void guncellebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncellebtnActionPerformed
        String istektipi;
        istektipi = istektipitxt.getText();
        try {
            Statement st = this.db.connect().createStatement();
            st.executeUpdate("update istek_tipleri set istek_tipi='" + istektipi + "'where istek_tipi_id=" + idsi);
            tabloyudoldur();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_guncellebtnActionPerformed

    private void silbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silbtnActionPerformed
        try {
            Statement st = this.db.connect().createStatement();
            st.executeUpdate("delete from istek_tipleri where istek_tipi_id=" + idsi);
            tabloyudoldur();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_silbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eklebtn;
    private javax.swing.JButton guncellebtn;
    private javax.swing.JTextField istektipitxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JButton secbtn;
    private javax.swing.JButton silbtn;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
